version: "3"

services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./postgres/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"

  elasticmq:
    container_name: elasticmq
    image: softwaremill/elasticmq:1.3.7
    expose:
      - 9324
      - 9325
    ports:
      - "9325:9325"
      - "9324:9324"
    volumes:
      - elasticmq-volume:/data
      - ./elasticmq/elasticmq.conf:/opt/elasticmq.conf

  reservation-app:
    container_name: reservation-app
    build: ./WebServices/ReservationApp/
    depends_on:
      - db
      - elasticmq
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default,docker

  movie-app:
    container_name: movie-app
    build: ./WebServices/MovieApp/
    depends_on:
      - db
      - elasticmq
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default,docker

  auth-app:
    container_name: auth-app
    build: ./WebServices/AuthApp/
    depends_on:
      - db
      - elasticmq
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default,docker

volumes:
  postgres-volume:
  elasticmq-volume:
